import type { Metadata } from 'next'

import './globals.css'
import Modal from '@/components/Modal'


export const metadata: Metadata = {
  title: 'Kanban Board',
  description: 'Generated by Aviral Singh',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-[#EEEDED]'>{children}
      <Modal/>
      </body>
    </html>
  )
}
